version: "3.7"

services:
  eureka:
    image: springcloud/eureka:latest
    ports:
      - 8761:8761
  microservicea:
    build:
      context: .
      dockerfile: microservicea.dockerfile
    volumes:
      - ./microservice-a:/var/www/app
    ports:
      - 3000:3000
  microserviceb:
    build:
      context: .
      dockerfile: microserviceb.dockerfile
    volumes:
      - ./microservice-b:/var/www/app
    ports:
      - 4000:4000
