version: "3.7"
services:
  app:
    build:
      dockerfile: ./.docker/app.dockerfile
      context: .
    entrypoint: ./.docker/entrypoint.sh
    container_name: api-todo-app
    networks:
      - api_todo_example_network
    ports:
      - "$COMPOSER_APP_PORT:$APP_PORT"
    env_file:
      - ./.env
    volumes:
      - "./:/var/www/app"

  mongodb:
    image: mongo:4.4.4
    restart: always
    volumes:
      - ./.docker/dbdata:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=secret
    networks:
      - api_todo_example_network

  mongo-express:
    image: mongo-express
    restart: unless-stopped
    ports:
      - "$COMPOSER_MONGO_EXPRESS_PORT:8081"
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_MONGODB_AUTH_USERNAME=root
      - ME_CONFIG_MONGODB_AUTH_PASSWORD=secret
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=secret
    networks:
      - api_todo_example_network
    depends_on:
      - mongodb



networks:
  api_todo_example_network:
    driver: bridge
